## 1. Set

In [1]:
set = {1, 2, 3, 4, 5, 'Hola'}

In [2]:
set.add(10)
set

{1, 10, 2, 3, 4, 5, 'Hola'}

In [3]:
set.add(10)
set

{1, 10, 2, 3, 4, 5, 'Hola'}

In [4]:
set1 = {1,2,3,4,5}

In [5]:
set2 = {5,6,7,8,9,4}

In [6]:
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [7]:
set1.intersection(set2)

{4, 5}

In [8]:
set1.difference(set2)

{1, 2, 3}

In [9]:
set2.difference(set1)

{6, 7, 8, 9}

In [10]:
set1.symmetric_difference(set2)

{1, 2, 3, 6, 7, 8, 9}

In [11]:
letras = { 'abc', 'dfg', 'hij'}
mayusculas = { l.upper() for l in letras}
mayusculas

{'ABC', 'DFG', 'HIJ'}

## 2. Numpy

In [12]:
import numpy as np

In [13]:
x = [1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [14]:
x = np.array([1,2,3,4,5,6], dtype = 'float')
x

array([1., 2., 3., 4., 5., 6.])

In [16]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.zeros_like(x)

array([0., 0., 0., 0., 0., 0.])

### 2.1 Rangos y Dimensiones

In [21]:
x = np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
# Dimensiones del tensor
x.shape #Cantidad de elementos que tiene cada dimensión

(10, 10)

In [23]:
#Rango del tensor
x.ndim #Cantidad de dimensiones

2

In [24]:
x[2,1]

0.0

In [25]:
x = np.array([[[10,20,30,40,50],
               [60,70,80,90,100]],
              [[100,200,300,400,500],
               [600,700,800,900,1000]]
             ])

x.shape

(2, 2, 5)

In [26]:
x[0, 1, 3]

90

In [27]:
x[1, 1, 4]

1000

### 2.2 Operaciones con Vectores

In [29]:
v = np.arange(1,6,1)
w = np.arange(6,11,1)

print(v + w)
print(v - w)
print(v * w)
print(v / w)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [30]:
#Broadcasting

v*2

array([ 2,  4,  6,  8, 10])

In [31]:
print(v/2)
print(v+5)
print(v-10)
print(v%2)

[0.5 1.  1.5 2.  2.5]
[ 6  7  8  9 10]
[-9 -8 -7 -6 -5]
[1 0 1 0 1]


In [32]:
x = [1, 2, 3]
x*2
#No hay broadcasting

[1, 2, 3, 1, 2, 3]

### 2.4 Funciones Universales


In [33]:
x = np.array([-2,-1,0,1,1,3,6])
x

array([-2, -1,  0,  1,  1,  3,  6])

In [35]:
print(np.sign(x))
print(np.abs(x))
print(np.cos(x))
print(np.sin(x))
print(np.exp(x))
print(np.log(x))


[-1 -1  0  1  1  1  1]
[2 1 0 1 1 3 6]
[-0.41614684  0.54030231  1.          0.54030231  0.54030231 -0.9899925
  0.96017029]
[-0.90929743 -0.84147098  0.          0.84147098  0.84147098  0.14112001
 -0.2794155 ]
[1.35335283e-01 3.67879441e-01 1.00000000e+00 2.71828183e+00
 2.71828183e+00 2.00855369e+01 4.03428793e+02]
[       nan        nan       -inf 0.         0.         1.09861229
 1.79175947]


/tmp/ipykernel_245/1421518739.py:6: RuntimeWarning: divide by zero encountered in log
  print(np.log(x))
/tmp/ipykernel_245/1421518739.py:6: RuntimeWarning: invalid value encountered in log
  print(np.log(x))


In [36]:
print(np.sqrt(x))

[       nan        nan 0.         1.         1.         1.73205081
 2.44948974]


/tmp/ipykernel_245/2965746161.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(x))


In [37]:
x = np.array([1,2,3,4,5,6,7,8,9,2,2])
x_nan = np.array([1,2,3,4,np.nan,6,8,10,np.nan])


In [38]:
np.mean(x)

4.454545454545454

In [40]:
np.mean(x_nan) #media para los casos donde hay nan
np.nanmean(x_nan) #media para los casos donde hay nan

4.857142857142857

In [42]:
print(np.max(x))
print(np.nanmax(x_nan))

9
10.0


In [43]:
print(np.min(x))
print(np.nanmin(x_nan))

1
1.0


In [44]:
print(np.var(x))
print(np.nanvar(x_nan))

6.793388429752068
9.26530612244898


In [45]:
print(np.std(x))
print(np.nanstd(x_nan))

2.6064129430602643
3.0438965360946453


In [46]:
print(np.prod(x))
print(np.nanprod(x_nan))

1451520
11520.0


In [47]:

#Posición del valor maximo
print(np.argmax(x))
print(np.nanargmax(x_nan))

8
7


In [48]:

#Posición del valor minimo
print(np.argmin(x))
print(np.nanargmin(x_nan))

0
0


In [49]:
print(np.median(x))
print(np.nanmedian(x_nan))

4.0
4.0
